name: Build Device Service
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: siamatic/smtrack-log-service:1.0.2-c
    - name: Send success message to slack
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "GitHub Action build siamatic/smtrack-log-service:1.0.2-c result: ${{ job.status }} 🖕🖕🖕🖕🖕",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build siamatic/smtrack-log-service:1.0.2-c result: ${{ job.status }} 🖕🖕🖕🖕🖕"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK